### ISSUE TITLE
RSS does not work

### ISSUE THREAD

**Issue by mayaka227** [Seia-Soto/Ohys-Fanmade#21]
The last feed is 22 days ago.

**Comment by seia-soto** [comment]
Thank you for writing issue as well!
Sorry for late reply. I was on study because of school exam. :<

A long time ago, but I'll explain.

It is actually not our problem, because Ohys-Fanmade is not Ohys-Raws. It is website based on Ohys-Raws JSON API(Unofficial, but you can find it from Ohys-Raws website). However, please write issue like this that I can make Ohys-Raws to notice. 👍
